### ISSUE TITLE
SimplexTree Deletion memory leak (iterative)

### ISSUE THREAD

**Issue by malottno** [wilseypa/lhf#10]
Deletion from the simplex tree (when using sliding window) does not delete the points from the neighborhood graph, leading to a memory leak where all points that have ever been inserted in the complex remain in the neighborhood graph (WEG). 

Need to fix and properly remove the deleted point from the WEG

**Comment by shcsywendy** [comment]
0401

**Comment by shcsywendy** [comment]
0401-1
