### ISSUE TITLE
BettiBoundaryTable output

### ISSUE THREAD

**Issue by malottno** [wilseypa/lhf#22]
Utils/writeOutput.cpp method writeBarcodes needs to be changed to write the bettiBoundaryTableEntry values defined in utils.hpp

Also should rename the file to not conflict with the debug output file. Currently the debug output file goes to args["outputFile"] and the bettis go to args["outputFile"] + .csv ; this probably should be args["outputFile"] + _debug and args["outputFile"] respectively.

**Comment by malottno** [comment]
@shcsywendy

**Comment by shcsywendy** [comment]
0401-2

**Comment by shcsywendy** [comment]
test 0401-4
