### ISSUE TITLE
kmeans++ fails with low k and data set size

### ISSUE THREAD

**Issue by malottno** [wilseypa/lhf#23]
With a small dataset (~6 points or so) and a small value of k (number of clusters), kmeans++ segfaults randomly. May be due to empty vectors inserted as partitions, not sure. 

`./LHF -i testData.csv -m reduced -k 5`

GDB output attached

![image](https://user-images.githubusercontent.com/7936066/78161413-65d6d480-7413-11ea-8837-c6af3fbe86f7.png)

**Comment by rishirv** [comment]
Fixed in #35
