### ISSUE TITLE
MPI mode needs to exec upscale when np < 2

### ISSUE THREAD

**Issue by malottno** [wilseypa/lhf#30]
Currently if np = 1 only the master process executes; this should really redirect to the reduced mode for single-process execution.

Run (MPI_Development) with:

`mpirun -np 1 ./LHF -i Circles.csv -m mpi`

(also segfaults)

![image](https://user-images.githubusercontent.com/7936066/79480242-dd902c00-7fdb-11ea-8550-bef7752f551e.png)

**Comment by shcsywendy** [comment]
https://github.com/wilseypa/lhf/commit/dd019aaeaa29274910becad24247934c652d3987
