### ISSUE TITLE
Performance disparity in debug mode (-x)

### ISSUE THREAD

**Issue by malottno** [wilseypa/lhf#43]
I noticed some of the performances change significantly between debug mode and non-debug mode. Seems when debug mode is enabled the fastPersistence pipe runs faster - need to look into this.

Run with:
`./LHF -i Circles.csv -m fast -x 1`
`./LHF -i Circles.csv -m fast`

See images below. Fast persistence with debug mode runs in ~0.001 seconds, while without debug mode it runs in ~0.007 seconds. Probably not directly an issue with fastPersistence, but needs to be explored to optimize.

![image](https://user-images.githubusercontent.com/7936066/80528558-21801b00-8964-11ea-91e0-86f81bb73929.png)

![image](https://user-images.githubusercontent.com/7936066/80528591-2e047380-8964-11ea-912e-332c9d7b948a.png)

**Comment by malottno** [comment]
Looks like it's only affecting fastpersistence (use -o console)

![image](https://user-images.githubusercontent.com/7936066/80532422-2051ec80-896a-11ea-96e3-c9a5530f92bc.png)

**Comment by rishirv** [comment]
@malottno This looks to be an issue with the the way the time is measured in the basePipe. When I print the time elapsed as measured by fastPersistence, the times are the same.

**Comment by malottno** [comment]
Fixed #60
