### ISSUE TITLE
MPI Branch : Partitition Size is zero sometime

### ISSUE THREAD

**Issue by rohitpalsingh-zz** [wilseypa/lhf#46]
![IMG_20200501_195711__01](https://user-images.githubusercontent.com/16203423/80862649-ad37c700-8c44-11ea-8312-744029e9eba5.jpg)

**Comment by malottno** [comment]
Looks like the last index of the labels array isn't being populated? @aaronsens any insight - k-means++ not generating enough labels?

Only seems to happen some of the time, more likely with higher value of k. I'll keep digging.

![image](https://user-images.githubusercontent.com/7936066/80873129-5e118680-8c84-11ea-87b4-c22d4ed6ac95.png)

**Comment by malottno** [comment]
Looks like the number of labels is 1 short of the data...

![image](https://user-images.githubusercontent.com/7936066/80873351-eba1a600-8c85-11ea-8404-24f1a1e2f9cb.png)

**Comment by malottno** [comment]
Fixed in master; kmeans+ was using comparison i < originaldata.size - 1.
